### PR TITLE
Send revenue as integer

### PR DESCRIPTION
**Pull request by harrisonkrat**

### CODE REVIEW

**Comment by harrisonkrat** [comment]
@byronopt will help provide context and address any issues to make sure this gets approved.

**Review by sweth — CHANGES_REQUESTED** [review]
Shouldn't that be 

= Math.round(revenue * 100)

**Comment by harrisonkrat** [comment]
@sweth My understanding of the code is that revenue is already part of the track.properties body, which has already been passed as payload.tags.revenue.  What we're checking here is if track.revenue actually contains some amount, and if so, since we already know it has been assigned to payload.tags.revenue, adjust payload.tags.revenue to be an integer.  At this point revenue and payload.tags.revenue are equivalent, so modifying payload.tags.revenue is appropriate.  The code as it currently stands does this.

**Comment by cbishop-sstk** [comment]
@harrisonkrat If thats the case I think it would be better to remove line 95 and do the check on payload.tags.revenue no?

**Comment by cbishop-sstk** [comment]
before the attributes update it didnt do this it used revenue inside 
  if (revenue) payload.revenue = revenue *= 100;

**Comment by harrisonkrat** [comment]
@cbishop-sstk My code works off of the latest master version where we are enabling the use of event tags for web, in which we pass the whole of track.properties, including track.revenue, into our tags object. Does your fork not yet pull from this latest master version?

We make the check against track.revenue so that we know to only apply Math.round() if some value was there, and then that value was passed to payload.tags.revenue.  If track.revenue returns a falsey value we won't bother with the rounding. If track.revenue is a string (empty or not), the rounding will return 0 or NaN; we'd accept the former but drop the latter, which would make sense.

**Comment by cbishop-sstk** [comment]
@harrisonkrat The concern is that the check isn't valid for what's being used inside the function and thus open to bugs.  I was just offering two suggestions for correction. Eliminating an unneeded var on 95 and just doing the check on payload.tags.revenue would be fine as well.

**Comment by sweth** [comment]
> We make the check against track.revenue so that we know to only apply Math.round() if some value was there, and then that value was passed to payload.tags.revenue. If track.revenue returns a falsey value we won't bother with the rounding. If track.revenue is a string (empty or not), the rounding will return 0 or NaN; we'd accept the former but drop the latter, which would make sense.

The question, though, is why test track.revenue rather than testing payload.tags.revenue.  Is there a situation where track.revenue will be truthy and payload.tags.revenue will be falsey?  If not, why not just test the thing that is going to be modified, to avoid having the implemented logic change if at some later point it does become the case that payload.tags.revenue can be seeded with a value different from track.revenue.

The current version will work now; we are just hoping to future-proof.

**Comment by harrisonkrat** [comment]
@byronopt please see the latest version of the PR here. Since track.revenue is already passed to payload.tags.revenue, we can apply the check and modification directly. Please pull in an eng resource if you think this needs a code review from our side.

**Comment by mikeproeng37** [comment]
Taking over for @harrisonkrat. @byronopt I will open up a PR from our Optimizely Github branch and go from there. Here is the PR for our own repo: https://github.com/optimizely/analytics.js-integration-optimizely/pull/3

**Comment by mikeproeng37** [comment]
I've put up another PR to address this: https://github.com/segment-integrations/analytics.js-integration-optimizely/pull/34

Please close this PR.

**Pull request closed without merging**
