### PR TITLE
Removed ID call

### PR DESCRIPTION
**Pull request by lucasoptimizely**
The setUserID function is an advanced Optimizely beta function. The function has a different effect than Optimizely customers expect and should therefore not be included in this integration at this point.

### CODE REVIEW

**Comment by f2prateek** [comment]
@lucasoptimizely please squash the commits.

I'm fine with this change. Will it have any adverse effects on existing customers who've expected the integration to work the way it currently does? Specifically my question is, should this be opt in via a setting?

cc @hankim813 @sperand-io

**Comment by lucasoptimizely** [comment]
@f2prateek The setUserId feature is a beta feature. The current standing is that we might never release the feature and sunset it altogether. We will go back to the drawing tables to build functionality that has behavior that meets our customer demand.

Since we might never release it and sunset it in the near term, I think an opt-in might not be necessary.

**Comment by lucasoptimizely** [comment]
@f2prateek I've squashed the commits. Is there anything else you need at the moment?

**Comment by hankim813** [comment]
@lucasoptimizely we'll deploy this by tomorrow afternoon :)

**Comment by lucasoptimizely** [comment]
@hankim813  Nice!

**Pull request merged**
