### PR TITLE
Implementing a method to track integration usage

### PR DESCRIPTION
**Pull request by lucasoptimizely**
Hi @hankim813,

We are reaching out to all our technology partners to implement the function I've added with this PR. It is our equivalent to [https://github.com/segment-integrations/analytics.js-integration-facebook-pixel/blob/master/lib/index.js#L37](https://github.com/segment-integrations/analytics.js-integration-facebook-pixel/blob/master/lib/index.js#L37)

I've taken the liberty to create a PR for you guys because by now I am pretty familiar with this code and it would be good to see some real data flow in as soon as possible. 

Hope you can check the PR.

Best,

Lucas

### CODE REVIEW

**Comment by f2prateek** [comment]
lgtm

**Comment by hankim813** [comment]
what is this for (in more detail) and does it have any affect on the customers' data? @lucasoptimizely @sperand-io

**Comment by lucasoptimizely** [comment]
It is a function so that we can see which of our customers are using the
integration. That helps us improve our APIs and create better experiences
for our customers.

**Comment by lucasoptimizely** [comment]
P.s. thanks Prateek for the quick turnaround

**Comment by hankim813** [comment]
Can you add a comment in the code to say that so future engineers know what it's doing? also we need a unit test for this added code. 

might need to make a new PR :) @lucasoptimizely

**Comment by lucasoptimizely** [comment]
Hi Han,

There is nothing to unittest. The only output is that a request is send to
our servers for 0.001 page view. There is no way to test for that. Also:
there is no comment in the Facebook code.

Since the code was merged I reported to the team that the code was
successfully merged in and I'll have to present the functionality tomorrow.
I kinda relied on the merge...

Lucas

**Comment by f2prateek** [comment]
@hankim813 yup I merged this because I don't think it affects our customers data (@lucasoptimizely can confirm), and hence didn't ask for tests.

As I understand it, this is for Optimizely's own internal analytics to detect that their customer is using their library via Segment. (@hankim813 like how we forward to heap and kahuna that an event is from segment).

**Comment by lucasoptimizely** [comment]
Correct!

**Comment by hankim813** [comment]
@f2prateek still think unit test is good principle. i actually pushed the pr just now https://github.com/segment-integrations/analytics.js-integration-optimizely/pull/15

**Pull request merged**
