### PR TITLE
Release 3.2.1

### PR DESCRIPTION
**Pull request by mikeproeng37**
@hankim813 can you take a look at this bug fix please?

### CODE REVIEW

**Review by hankim813 — APPROVED** [review]
LGTM! we'll get this shipped next week!

**Comment by hankim813** [comment]
@mikeng13 can you update the `package.json` version as well?

**Comment by mikeproeng37** [comment]
Will do Han!

**Comment by mikeproeng37** [comment]
@hankim813 looks like you've run out of minutes with SauceLabs so the test failed

**Comment by hankim813** [comment]
@mikeng13 deployed! Thanks for the fix

**Pull request merged**
